pipeline {
    agent any
    stages{
        stage(stage1){
            steps{
            echo "this is stage 1"
           }
        }
        stage(stage2){
           steps{
             echo "this is stage 2"
           }
        }
        stage(stage3){
            steps{
                echo "this is stage3"
            }
        }
        stage(stage4){
            steps{
                echo "this is stage4"
            }
        }
        stage(stage5){
            steps{
                echo "this is stage5"
            }
        }
    }

}
